nats:
    url: nats://localhost:4222
    cluster_id: "clusterID"
    client_id: "clientID"
    canal: "orders"
    subject: subject
    queue_group: "group"
    dur_name: "name"
db:
    dbhost: localhost
    dbport: 5432
    dbuser: postgres
    dbpassword: root
    dbname: orders
    dbsslmode: disable
serv:
    port: 8080
    host: localhost
