nats:
    url: nats://localhost:4222
    cluster_id: "clusterID"
    client_id: "clientID"
    subject: subject
db:
    dbhost: localhost
    dbport: 5432
    dbuser: postgres
    dbpassword: root
    dbname: orders
    dbsslmode: disable
